plugins {
	id 'java'
	id 'xyz.wagyourtail.unimined' version '1.4.1-SNAPSHOT' apply false
}

group project.maven_group

base {
	archivesName = project.archives_base_name
}

allprojects {
	apply(plugin: "xyz.wagyourtail.unimined")

	version project.version

	unimined.useGlobalCache = false

	unimined.fabricMaven()
	unimined.legacyFabricMaven()
	unimined.modrinthMaven()
	unimined.wagYourMaven("releases")
	unimined.jitpack()

	configurations {
		clientOfficialImplementation
		serverOfficialImplementation
		modImplementation.extendsFrom clientOfficialImplementation
		modImplementation.extendsFrom serverOfficialImplementation
	}

	unimined.minecraft(sourceSets.main, true) {
		version project.minecraft_version

		mappings {
			babricIntermediary()
			biny(project.mappings_version)
		}

		legacyFabric {
			loader project.fabric_version

			customIntermediaries = true
			prodNamespace("babricIntermediary")

			if (project.hasProperty("access_widener") && !project.access_widener.isEmpty()) {
				accessWidener(project.file(project.access_widener))
			}
		}

		mods.remap(configurations.clientOfficialImplementation) {
			namespace("clientOfficial")
		}

		mods.remap(configurations.serverOfficialImplementation) {
			namespace("serverOfficial")
		}
	}

	dependencies {
		modImplementation("com.github.thecatcore.CursedMixinExtensions:fabric:1.0.0") {
			exclude(module: 'fabric-loader')
		}
		// Published version of MRAPI
//		modImplementation("maven.modrinth:mod-remapping-api:${project.mod_remapping_api}")

//        // Local version of MRAPI
//        modImplementation("io.github.fabriccompatibilitylayers:mod-remapping-api:1.27.0")

//		modImplementation(fabricApi.legacyFabricModule("legacy-fabric-logger-api-v1", "1.9.1+1.12.2")) {
//			exclude(module: 'fabric-loader')
//		}
//		modImplementation("maven.modrinth:spasm:0.2")
//
//		modImplementation("com.github.thecatcore:WFVAIO:1.2.1") {
//			exclude(module: 'fabric-loader')
//		}

		implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:0.5.0-rc.2"))

		// Babric mods&co
		implementation "org.slf4j:slf4j-api:1.8.0-beta4"
		implementation 'org.apache.logging.log4j:log4j-slf4j18-impl:2.17.2'
		implementation "blue.endless:jankson:1.2.1"

//		modImplementation "net.modificationstation:StationAPI:${project.stapi_version}"

		// Babric ModMenu
		modImplementation("net.glasslauncher.mods:ModMenu:1.8.5-beta.11") {
			transitive false
		}
	}

	java {
		sourceCompatibility = JavaVersion.VERSION_1_8
		targetCompatibility = JavaVersion.VERSION_1_8
	}

	processResources {
		inputs.property "version", project.version
		inputs.property "mc_version", project.minecraft_version
		inputs.property "mrapi_version", project.mod_remapping_api

		filesMatching("fabric.mod.json") {
			expand "version": project.version,
				"mc_version": rootProject.minecraft_version,
				"mrapi_version": project.mod_remapping_api
		}
	}
}

unimined.minecraft {
}

subprojects.forEach {
	remapJar.dependsOn("${it.path}:remapJar")
}

dependencies {
	clientOfficialImplementation "risugami:modloader:b1.7.3"
	clientOfficialImplementation "modloadermp:modloadermp:b1.7.3:client"
	clientOfficialImplementation "net.minecraftforge:forge:b1.7.3-1.0.7:client@zip"
	serverOfficialImplementation "modloadermp:modloadermp:b1.7.3:server"
	serverOfficialImplementation "net.minecraftforge:forge:b1.7.3-1.0.7:server@zip"

	afterEvaluate {
		subprojects.forEach {
			include(project(path: "${it.path}", configuration: 'production'))
		}
	}
}
